name: .NET CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
      - "release/**"
      - "hotfix/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore D4U.Api/D4U.Api.csproj

      - name: Build
        run: dotnet build D4U.Api/D4U.Api.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build
        continue-on-error: true
